#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d web discord dev games other   

bspc config window_gap 12
bspc config focused_border_color "#ABE9B3"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle     true 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a robloxstudiolauncherbeta.exe state=floating
bspc rule -a robloxplayerlauncher.exe state=floating

picom -b
nitrogen --restore
$HOME/.config/polybar/launch.sh
$HOME/node_behavior.sh
